---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - bower_components

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g bower

install:
  - yarn install
  - bower install

before_script:
  - ember sauce:connect

script:
  - COVERAGE=true ember test

after_script:
  - ember sauce:disconnect
  - cat coverage/lcov.info | coveralls

env:
  global:
    - SAUCE_USERNAME=adsy-timed
    - SAUCE_ACCESS_KEY=2ce2a4cf-10cb-4af8-9429-3506d16b3a35
