---
language: node_js
node_js:
  - "6"

addons:
  firefox: "latest"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - bower_components

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - yarn install
  - bower install

script:
  - COVERAGE=true ember test

after_script:
  - cat coverage/lcov.info | coveralls
