---
language: node_js
node_js:
  - "8"

addons:
  firefox: latest
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test

after_success:
  - yarn run coveralls

env:
  - COVERAGE=true JOBS=2
