---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install

script:
  - ember test --test-port 7000

after_script:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls

env:
  global:
    - COVERAGE=true
