version: "3"

services:
  frontend:
    image: danlynn/ember-cli:latest
    depends_on:
      - backend
    volumes:
      - .:/myapp
      - ./node_modules:/myapp/node_modules
    tmpfs:
      - /myapp/tmp
    ports:
      - 4200:4200
      - 7020:7020
      - 7357:7357
    command: ember server --proxy=http://backend

  backend:
    depends_on:
      - mailhog
    environment:
      - EMAIL_URL=smtp://mailhog:1025
    command: /bin/sh -c "wait-for-it.sh -t 60 db:5432 -- ./manage.py migrate && ./manage.py loaddata timed/fixtures/test_data.json && uwsgi"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    environment:
      - MH_UI_WEB_PATH=mailhog

volumes:
  node_modules:
