name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      # TODO: delete when upgrade is done
      - ember-octane

env:
  NODE_VERSION: 16

jobs:
  lint:
    name: Lint
    runs-on: [ubuntu-latest]
    timeout-minutes: 5

    strategy:
      matrix:
        # TODO add hbs
        target: [js]

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.17.1

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint ${{ matrix.target }}
        run: pnpm lint:${{ matrix.target }}

  test:
    name: Tests
    needs: [lint]
    runs-on: [ubuntu-latest]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.17.1

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
        env:
          COVERAGE: true

        # TODO enable this again after flaky tests are added back
#       - name: Upload coverage report to Codecov
#         uses: codecov/codecov-action@v1
#         with:
#           file: ./coverage/lcov.info
